name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'  # or 'oracle'
        java-version: '21'

    - name: Build with Maven (skip tests)
      run: mvn -B clean package -DskipTests

    - name: Archive built JAR(s)
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run tests with Maven
      run: mvn -B test
